# config.py
API_KEY = 'Hqod6Y5MDAkMmAJbRKOqUUDsYb9HG5aAkE3BMPZxHrm8JdZTgfIJr2RKSkRiOlDM'
API_SECRET = 'wVI5YTy9Y3dhiU1KoOSc0ysMVsAvaklSHDm40ZqkaHzKGgjlq9zlmi5CSF3n2wGw'
SECRET = 'eyJhbGciOiJIUzI1NiJ9.eyJzaWduYWxzX3NvdXJjZV9pZCI6MTAyNTR9.UpdSFm3FpcmR7hcVaBUOzPp5Q6-1gBRlQA21sH0ieHo'
THREE_COMMAS_WEBHOOK_URL = 'https://api.3commas.io/signal_bots/webhooks'
SELECTED_SYMBOLS = ['ID/USDT', 'INJ/USDT', 'JASMY/USDT', 'JOE/USDT', 'JTO/USDT', 
 'JUP/USDT', 'KEY/USDT', 'KLAY/USDT', 'LDO/USDT', 'LEVER/USDT', 
 'LINA/USDT', 'LINK/USDT', 'LIT/USDT', 'LSK/USDT', 'LTC/USDT', 
 'MAGIC/USDT', 'MANTA/USDT', 'MASK/USDT', 'MATIC/USDT', 'MEME/USDT', 
 'METIS/USDT', 'MINA/USDT', 'NEAR/USDT', 'NKN/USDT', 'OGN/USDT', 
 'OMG/USDT', 'OMNI/USDT', 'ONE/USDT', 'ONG/USDT', 'OP/USDT']
