# config.py
API_KEY = 'Hqod6Y5MDAkMmAJbRKOqUUDsYb9HG5aAkE3BMPZxHrm8JdZTgfIJr2RKSkRiOlDM'
API_SECRET = 'wVI5YTy9Y3dhiU1KoOSc0ysMVsAvaklSHDm40ZqkaHzKGgjlq9zlmi5CSF3n2wGw'
SECRET = 'eyJhbGciOiJIUzI1NiJ9.eyJzaWduYWxzX3NvdXJjZV9pZCI6MTAyNTR9.UpdSFm3FpcmR7hcVaBUOzPp5Q6-1gBRlQA21sH0ieHo'
THREE_COMMAS_WEBHOOK_URL = 'https://api.3commas.io/signal_bots/webhooks'
SELECTED_SYMBOLS = SELECTED_SYMBOLS = [
    'MINA/USDT', 'NEAR/USDT', 'NKN/USDT', 'OGN/USDT', 'OMG/USDT', 
    'PENDLE/USDT', 'PEOPLE/USDT', 'PHB/USDT', 'PORTAL/USDT', 'FIDA/USDT', 
    'POWR/USDT', 'PYTH/USDT', 'REN/USDT', 'REZ/USDT', 'NEIRO/USDT', 
    'ROSE/USDT', 'RSR/USDT', 'RUNE/USDT', 'RVN/USDT', 'SAGA/USDT', 
    'SAND/USDT', 'SEI/USDT', 'SNX/USDT', 'SOL/USDT', 'QUICK/USDT', 
    'SPELL/USDT', 'STEEM/USDT', 'STG/USDT', 'STMX/USDT', 'STORJ/USDT', 
    'STRK/USDT', 'STX/USDT', 'SUI/USDT', 'SUPER/USDT', 'SUSHI/USDT', 
    'SXP/USDT', 'THETA/USDT', 'TLM/USDT', 'REI/USDT', 'FLM/USDT', 
    'TNSR/USDT', 'TRB/USDT', 'FLUX/USDT', 'GHST/USDT', 'HMSTR/USDT', 
    'TRX/USDT', 'TWT/USDT', 'UMA/USDT', 'UNFI/USDT', 'UNI/USDT', 
    'WLD/USDT', 'XEM/USDT', 'XLM/USDT', 'AERGO/USDT', 'BSW/USDT', 
    'XMR/USDT', 'XRP/USDT', 'XTZ/USDT', 'CATI/USDT', 'ZK/USDT', 
    'XVS/USDT', 'ZEC/USDT', 'ZEN/USDT', 'ZRO/USDT', 'ZIL/USDT', 'POL/USDT'
]
