# config.py
API_KEY = 'Hqod6Y5MDAkMmAJbRKOqUUDsYb9HG5aAkE3BMPZxHrm8JdZTgfIJr2RKSkRiOlDM'
API_SECRET = 'wVI5YTy9Y3dhiU1KoOSc0ysMVsAvaklSHDm40ZqkaHzKGgjlq9zlmi5CSF3n2wGw'
SECRET = 'eyJhbGciOiJIUzI1NiJ9.eyJzaWduYWxzX3NvdXJjZV9pZCI6MTAyNTR9.UpdSFm3FpcmR7hcVaBUOzPp5Q6-1gBRlQA21sH0ieHo'
THREE_COMMAS_WEBHOOK_URL = 'https://api.3commas.io/signal_bots/webhooks'
SELECTED_SYMBOLS = ['PENDLE/USDT', 'PEOPLE/USDT', 'PHB/USDT', 'PORTAL/USDT',
 'POWR/USDT', 'PYTH/USDT', 'REN/USDT', 'REZ/USDT', 'ROSE/USDT',
 'RSR/USDT', 'RUNE/USDT', 'RVN/USDT', 'SAGA/USDT', 'SAND/USDT',
 'SEI/USDT', 'SNX/USDT', 'SOL/USDT', 'SPELL/USDT', 'STEEM/USDT',
 'STG/USDT', 'STMX/USDT', 'STORJ/USDT', 'STRK/USDT', 'STX/USDT',
 'SUI/USDT', 'SUPER/USDT', 'SUSHI/USDT', 'SXP/USDT', 'THETA/USDT']
