# config.py
API_KEY = 'aSPkiWrlnLzest6sUOmxz8tIY06v7MzAmdkUxRFupomyj3400MABC0k0wr5erTCE'
API_SECRET = 'JZGHUi2b8B1pQBD2zf1kKnJr7h18P8vghVN3JrVvgP5WD9WnvylW3HETXGERMJo3'
SECRET = 'eyJhbGciOiJIUzI1NiJ9.eyJzaWduYWxzX3NvdXJjZV9pZCI6MTAyNTR9.UpdSFm3FpcmR7hcVaBUOzPp5Q6-1gBRlQA21sH0ieHo'
THREE_COMMAS_WEBHOOK_URL = 'https://api.3commas.io/signal_bots/webhooks'
SELECTED_SYMBOLS = ['DYDX/USDT', 'DYM/USDT', 'EDU/USDT', 'EGLD/USDT', 'ENA/USDT',
 'ENJ/USDT', 'ENS/USDT', 'EOS/USDT', 'ETC/USDT', 'ETHFI/USDT',
 'ETH/USDT', 'FET/USDT', 'FIL/USDT', 'FLM/USDT',
 'FLOW/USDT', 'FRONT/USDT', 'FTM/USDT', 'FXS/USDT', 'GAS/USDT',
 'GLM/USDT', 'GMX/USDT', 'GRT/USDT', 'GTC/USDT', 'HBAR/USDT',
 'HFT/USDT', 'HIFI/USDT', 'HIGH/USDT', 'HOOK/USDT', 'ICP/USDT']
