# config.py
API_KEY = 'Hqod6Y5MDAkMmAJbRKOqUUDsYb9HG5aAkE3BMPZxHrm8JdZTgfIJr2RKSkRiOlDM'
API_SECRET = 'wVI5YTy9Y3dhiU1KoOSc0ysMVsAvaklSHDm40ZqkaHzKGgjlq9zlmi5CSF3n2wGw'
SECRET = 'eyJhbGciOiJIUzI1NiJ9.eyJzaWduYWxzX3NvdXJjZV9pZCI6MTAyNTR9.UpdSFm3FpcmR7hcVaBUOzPp5Q6-1gBRlQA21sH0ieHo'
THREE_COMMAS_WEBHOOK_URL = 'https://api.3commas.io/signal_bots/webhooks'
SELECTED_SYMBOLS = ['TLM/USDT', 'TNSR/USDT', 'TRB/USDT', 'TRX/USDT', 'TWT/USDT',
 'UMA/USDT', 'UNFI/USDT', 'UNI/USDT', 'VANRY/USDT', 'VET/USDT',
 'WAXP/USDT', 'WLD/USDT', 'XEM/USDT', 'XLM/USDT', 'XMR/USDT',
 'XRP/USDT', 'XTZ/USDT', 'XVS/USDT', 'ZEC/USDT', 'ZEN/USDT',
 'ZIL/USDT', 'ZK/USDT', 'ZRO/USDT', 'ZRX/USDT']
