# config.py
API_KEY = 'Hqod6Y5MDAkMmAJbRKOqUUDsYb9HG5aAkE3BMPZxHrm8JdZTgfIJr2RKSkRiOlDM'
API_SECRET = 'wVI5YTy9Y3dhiU1KoOSc0ysMVsAvaklSHDm40ZqkaHzKGgjlq9zlmi5CSF3n2wGw'
SECRET = 'eyJhbGciOiJIUzI1NiJ9.eyJzaWduYWxzX3NvdXJjZV9pZCI6MTAyNTR9.UpdSFm3FpcmR7hcVaBUOzPp5Q6-1gBRlQA21sH0ieHo'
THREE_COMMAS_WEBHOOK_URL = 'https://api.3commas.io/signal_bots/webhooks'
SELECTED_SYMBOLS = ['1INCH/USDT', 'ARPA/USDT', 'BIGTIME/USDT', 'CHR/USDT', 'DYDX/USDT', 'FTM/USDT', 'ID/USDT', 'LINA/USDT', 'MINA/USDT', 'ONT/USDT', 'REN/USDT', 'STMX/USDT', 'T/USDT', 'XMR/USDT',
'AAVE/USDT', 'AR/USDT', 'BLUR/USDT', 'CHZ/USDT', 'DYM/USDT', 'FXS/USDT', 'ILV/USDT', 'LINK/USDT', 'MKR/USDT', 'OP/USDT', 'REZ/USDT', 'STORJ/USDT', 'TWT/USDT', 'XRP/USDT',
'ACE/USDT', 'ASTR/USDT', 'BLZ/USDT', 'CKB/USDT', 'EDU/USDT', 'GALA/USDT', 'IMX/USDT', 'LISTA/USDT', 'MOVR/USDT', 'ORBS/USDT', 'RIF/USDT', 'STRK/USDT', 'UMA/USDT', 'XTZ/USDT',
'ACH/USDT', 'ATA/USDT', 'BNB/USDT', 'COMBO/USDT', 'EGLD/USDT', 'GAS/USDT', 'INJ/USDT', 'LIT/USDT', 'MTL/USDT', 'PENDLE/USDT', 'RLC/USDT', 'STX/USDT', 'UNFI/USDT', 'XVS/USDT',
'ADA/USDT', 'ATOM/USDT', 'BNT/USDT', 'COMP/USDT', 'EIGEN/USDT', 'GHST/USDT', 'IOST/USDT', 'LOKA/USDT', 'MYRO/USDT', 'PEOPLE/USDT', 'RONIN/USDT', 'SUI/USDT', 'UNI/USDT', 'YFI/USDT',
'AERGO/USDT', 'AUCTION/USDT', 'BNX/USDT', 'COS/USDT', 'ENA/USDT', 'GLM/USDT', 'IOTA/USDT', 'LOOM/USDT', 'NEAR/USDT', 'PERP/USDT', 'ROSE/USDT', 'SUN/USDT', 'USDC/USDT', 'YGG/USDT',
'AEVO/USDT', 'AVAX/USDT', 'BOME/USDT', 'COTI/USDT', 'ENJ/USDT', 'GMT/USDT', 'IOTX/USDT', 'LPT/USDT', 'PHB/USDT', 'RPL/USDT', 'SUPER/USDT', 'USTC/USDT',
'ALGO/USDT', 'AXL/USDT', 'CRV/USDT', 'ENS/USDT', 'GMX/USDT', 'IO/USDT', 'LQTY/USDT', 'NEO/USDT', 'PIXEL/USDT', 'RSR/USDT', 'SUSHI/USDT', 'UXLINK/USDT',
'ALICE/USDT', 'AXS/USDT', 'BRETT/USDT', 'CTSI/USDT', 'EOS/USDT', 'GRT/USDT', 'JASMY/USDT', 'LRC/USDT', 'NFP/USDT', 'POL/USDT', 'RUNE/USDT', 'SXP/USDT', 'VANRY/USDT',
'ALPACA/USDT', 'AXS/USDT', 'BADGER/USDT', 'BSV/USDT', 'CYBER/USDT', 'ETC/USDT', 'GTC/USDT', 'JOE/USDT', 'LSK/USDT', 'NKN/USDT', 'POLYX/USDT', 'RVN/USDT', 'SYN/USDT', 'VET/USDT', 
'ALT/USDT', 'ALPHA/USDT', 'ANKR/USDT', 'APE/USDT', 'API3/USDT', 'APT/USDT', 'ARB/USDT', 'ARK/USDT', 'ARKM/USDT', 'BAL/USDT', 'BANANA/USDT', 'BAT/USDT', 'BCH/USDT', 'BEAMX/USDT', 'BEL/USDT', 'BICO/USDT', 'BSV/USDT', 'BSW/USDT', 'BTCDOM/USDT', 'BTC/USDT', 
'CAKE/USDT', 'CATI/USDT', 'CELO/USDT', 'CELR/USDT', 'CFX/USDT', 'CHESS/USDT', 'COMP/USDT', 'DAR/USDT', 'DASH/USDT', 'DENT/USDT', 'DEFI/USDT', 'DIA/USDT', 'DOGE/USDT', 'DOGS/USDT', 'DODOX/USDT', 'DOT/USDT', 'DUSK/USDT',
'ENJ/USDT', 'EOS/USDT', 'ETC/USDT', 'ETH/USDT', 'ETHFI/USDT', 'ETHW/USDT', 'FET/USDT', 'FIDA/USDT', 'FIL/USDT', 'FLOW/USDT', 'FLM/USDT', 'FLUX/USDT', 'FTM/USDT', 'G/USDT', 'GALA/USDT', 'GHST/USDT', 'GTC/USDT', 'HBAR/USDT', 'HIGH/USDT', 'HIFI/USDT', 
'HMSTR/USDT', 'HOOK/USDT', 'HOT/USDT', 'ICP/USDT', 'ICX/USDT', 'ID/USDT', 'ILV/USDT', 'IMX/USDT', 'IO/USDT', 'IOST/USDT', 'IOTA/USDT', 'IOTX/USDT', 'JASMY/USDT', 'JTO/USDT', 'KAS/USDT', 'KAVA/USDT', 'KDA/USDT', 'KEY/USDT', 'KLAY/USDT', 'KNC/USDT', 'KSM/USDT', 'LDO/USDT', 'LEVER/USDT', 'LIT/USDT', 
'LINK/USDT', 'LISTA/USDT', 'LPT/USDT', 'LRC/USDT', 'LSK/USDT', 'LTC/USDT', 'LUNA2/USDT', 
'MAGIC/USDT', 'MANA/USDT', 'MASK/USDT', 'MAV/USDT', 'MAVIA/USDT', 'MBOX/USDT', 'MEW/USDT', 'METIS/USDT', 'MKR/USDT', 'MOVR/USDT', 'MYRO/USDT', 'NFP/USDT', 'NEAR/USDT', 'NEIRO/USDT', 
'NEO/USDT', 'NKN/USDT', 'NMR/USDT', 'NTRN/USDT', 'NULS/USDT', 'OGN/USDT', 'OM/USDT', 'OMG/USDT', 'OMNI/USDT', 'ONG/USDT', 'OP/USDT', 'ORBS/USDT', 'PEOPLE/USDT', 'PERP/USDT', 'PHB/USDT', 'PIXEL/USDT', 'POPCAT/USDT', 'POWR/USDT', 'PORTAL/USDT', 'QTUM/USDT', 'QUICK/USDT', 'QNT/USDT', 'RARE/USDT', 'REEF/USDT', 'REI/USDT', 'REN/USDT', 'RENDER/USDT', 'RLC/USDT', 'RONIN/USDT', 
'ROSE/USDT', 'RSR/USDT', 'RUNE/USDT', 'SAGA/USDT', 'SAND/USDT', 'SKL/USDT', 'SNX/USDT', 'SOL/USDT', 'SPELL/USDT', 'SFP/USDT'
]