# config.py
API_KEY = 'eYZfT3hBAT7otTJiZ1RDU7RACjtpJXsOF4iIGlXfWZUm5PnKQ7OOgiSsfyWKZntp'
API_SECRET = 'aWXYLo6PukZ3qs47nKJN6FhPtk0DWpULZWlLLqzFoJR6PTkq4rsCBsKBlWznhLhI'
SECRET = 'eyJhbGciOiJIUzI1NiJ9.eyJzaWduYWxzX3NvdXJjZV9pZCI6MTAyNTR9.UpdSFm3FpcmR7hcVaBUOzPp5Q6-1gBRlQA21sH0ieHo'
THREE_COMMAS_WEBHOOK_URL = 'https://api.3commas.io/signal_bots/webhooks'
SELECTED_SYMBOLS = ['BCH/USDT', 'BEAMX/USDT', 'BEL/USDT', 'BICO/USDT',
 'BLUR/USDT', 'BLZ/USDT', 'BNB/USDT', 'BNT/USDT', 'BNX/USDT',
 'BOME/USDT', 'BOND/USDT', 'BSV/USDT', 'BTC/USDT',
 'CAKE/USDT', 'CELO/USDT', 'CELR/USDT', 'CFX/USDT', 'CHR/USDT',
 'CKB/USDT', 'COMBO/USDT', 'COTI/USDT', 'CRV/USDT',
 'CTSI/USDT', 'CYBER/USDT', 'DAR/USDT', 'DASH/USDT',
 'DENT/USDT', 'DOGE/USDT', 'DOT/USDT', 'DUSK/USDT']
