# config.py
API_KEY = 'Hqod6Y5MDAkMmAJbRKOqUUDsYb9HG5aAkE3BMPZxHrm8JdZTgfIJr2RKSkRiOlDM'
API_SECRET = 'wVI5YTy9Y3dhiU1KoOSc0ysMVsAvaklSHDm40ZqkaHzKGgjlq9zlmi5CSF3n2wGw'
SECRET = 'eyJhbGciOiJIUzI1NiJ9.eyJzaWduYWxzX3NvdXJjZV9pZCI6MTAyNTR9.UpdSFm3FpcmR7hcVaBUOzPp5Q6-1gBRlQA21sH0ieHo'
THREE_COMMAS_WEBHOOK_URL = 'https://api.3commas.io/signal_bots/webhooks'
SELECTED_SYMBOLS = ['1INCH/USDT', 'ARPA/USDT', 'BIGTIME/USDT', 'CHR/USDT', 'DYDX/USDT', 'FTM/USDT', 'ID/USDT', 'LINA/USDT', 'MINA/USDT', 'ONT/USDT', 'REN/USDT', 'STMX/USDT', 'T/USDT',
'AAVE/USDT', 'AR/USDT', 'BLUR/USDT', 'CHZ/USDT', 'DYM/USDT', 'FXS/USDT', 'ILV/USDT', 'LINK/USDT', 'MKR/USDT', 'OP/USDT', 'REZ/USDT', 'STORJ/USDT', 'TWT/USDT', 'XRP/USDT', 'XMR/USDT',
'ACE/USDT', 'ASTR/USDT', 'BLZ/USDT', 'CKB/USDT', 'EDU/USDT', 'GALA/USDT', 'IMX/USDT', 'LISTA/USDT', 'MOVR/USDT', 'ORBS/USDT', 'RIF/USDT', 'STRK/USDT', 'UMA/USDT', 'XTZ/USDT',
'ACH/USDT', 'ATA/USDT', 'BNB/USDT', 'COMBO/USDT', 'EGLD/USDT', 'GAS/USDT', 'INJ/USDT', 'LIT/USDT', 'MTL/USDT', 'PENDLE/USDT', 'RLC/USDT', 'STX/USDT', 'UNFI/USDT', 'XVS/USDT',
'ADA/USDT', 'ATOM/USDT', 'BNT/USDT', 'COMP/USDT', 'EIGEN/USDT', 'GHST/USDT', 'IOST/USDT', 'LOKA/USDT', 'MYRO/USDT', 'PEOPLE/USDT', 'RONIN/USDT', 'SUI/USDT', 'UNI/USDT', 'YFI/USDT',
'AERGO/USDT', 'AUCTION/USDT', 'BNX/USDT', 'COS/USDT', 'ENA/USDT', 'GLM/USDT', 'IOTA/USDT', 'LOOM/USDT', 'NEAR/USDT', 'PERP/USDT', 'ROSE/USDT', 'SUN/USDT', 'USDC/USDT', 'YGG/USDT',
'AEVO/USDT', 'AVAX/USDT', 'BOME/USDT', 'COTI/USDT', 'ENJ/USDT', 'GMT/USDT', 'IOTX/USDT', 'LPT/USDT', 'PHB/USDT', 'RPL/USDT', 'SUPER/USDT', 'USTC/USDT', 'DODOX/USDT', 'DOT/USDT', 'DUSK/USDT',
'ALGO/USDT', 'AXL/USDT', 'CRV/USDT', 'ENS/USDT', 'GMX/USDT', 'IO/USDT', 'LQTY/USDT', 'NEO/USDT', 'PIXEL/USDT', 'RSR/USDT', 'SUSHI/USDT', 'UXLINK/USDT', 'HBAR/USDT', 'HIGH/USDT', 'HIFI/USDT', 
'ALICE/USDT', 'AXS/USDT', 'BRETT/USDT', 'CTSI/USDT', 'EOS/USDT', 'GRT/USDT', 'JASMY/USDT', 'LRC/USDT', 'NFP/USDT', 'POL/USDT', 'RUNE/USDT', 'SXP/USDT', 'VANRY/USDT', 'GTC/USDT'
]
