# config.py
API_KEY = 'Hqod6Y5MDAkMmAJbRKOqUUDsYb9HG5aAkE3BMPZxHrm8JdZTgfIJr2RKSkRiOlDM'
API_SECRET = 'wVI5YTy9Y3dhiU1KoOSc0ysMVsAvaklSHDm40ZqkaHzKGgjlq9zlmi5CSF3n2wGw'
SECRET = 'eyJhbGciOiJIUzI1NiJ9.eyJzaWduYWxzX3NvdXJjZV9pZCI6MTAyNTR9.UpdSFm3FpcmR7hcVaBUOzPp5Q6-1gBRlQA21sH0ieHo'
THREE_COMMAS_WEBHOOK_URL = 'https://api.3commas.io/signal_bots/webhooks'
SELECTED_SYMBOLS = [
    'AAVE/USDT', 'ADA/USDT', 'AEVO/USDT', 'AGLD/USDT', 'ALGO/USDT'  
    'ALICE/USDT', 'ALPHA/USDT', 'ALT/USDT', 'AMB/USDT', 'APT/USDT'  
    'AR/USDT', 'ARB/USDT', 'ARK/USDT', 'ARPA/USDT', 'ASTR/USDT'  
    'ATA/USDT', 'ATOM/USDT', 'AUCTION/USDT', 'AVAX/USDT', 'AXL/USDT'  
    'AXS/USDT', 'BADGER/USDT', 'BAKE/USDT', 'BAL/USDT', 'BAND/USDT'  
    'BAT/USDT', 'BB/USDT', 'BCH/USDT', 'BEAMX/USDT', 'BEL/USDT'  
    'BICO/USDT', 'BLUR/USDT', 'BLZ/USDT', 'BNB/USDT', 'BNT/USDT'  
    'BNX/USDT', 'BOME/USDT', 'BOND/USDT', 'BSV/USDT', 'BTC/USDT'  
    'CAKE/USDT', 'CELO/USDT', 'CELR/USDT', 'CFX/USDT', 'CHR/USDT'  
    'CKB/USDT', 'COMBO/USDT', 'COTI/USDT', 'CRV/USDT', 'CTSI/USDT'  
    'CYBER/USDT', 'DAR/USDT', 'DASH/USDT', 'LTC/USDT', 'MAGIC/USDT'  
    'MANTA/USDT', 'OMNI/USDT', 'ZRX/USDT'
]
  # Add your desired symbols
