# config.py
API_KEY = 'GxSSU0ESNuGIwTjG9X13eZlKU4dbsJzPbW2vsNiezRkSEGz69u7zajLz7WdYX1Xr'
API_SECRET = 'YpBOWSjtLXKPPGMi3r0pbDAy6pMgAZZ5KOArqPLmth7d5k4U2gKNzisrsKGe0fn5'
SECRET = 'eyJhbGciOiJIUzI1NiJ9.eyJzaWduYWxzX3NvdXJjZV9pZCI6MTAyNTR9.UpdSFm3FpcmR7hcVaBUOzPp5Q6-1gBRlQA21sH0ieHo'
THREE_COMMAS_WEBHOOK_URL = 'https://api.3commas.io/signal_bots/webhooks'
SELECTED_SYMBOLS = [
'ALPACA/USDT', 'AXS/USDT', 'BADGER/USDT', 'BSV/USDT', 'CYBER/USDT', 'ETC/USDT', 'GTC/USDT', 'JOE/USDT', 'LSK/USDT', 'NKN/USDT', 'POLYX/USDT', 'RVN/USDT', 'SYN/USDT', 'VET/USDT', 
'ALT/USDT', 'ALPHA/USDT', 'ANKR/USDT', 'APE/USDT', 'API3/USDT', 'APT/USDT', 'ARB/USDT', 'ARK/USDT', 'ARKM/USDT', 'BAL/USDT', 'BANANA/USDT', 'BAT/USDT', 'BCH/USDT', 'BEAMX/USDT', 
'CAKE/USDT', 'CATI/USDT', 'CELO/USDT', 'CELR/USDT', 'CFX/USDT', 'CHESS/USDT', 'COMP/USDT', 'DAR/USDT', 'DASH/USDT', 'DENT/USDT', 'DEFI/USDT', 'DIA/USDT', 'DOGE/USDT', 'DOGS/USDT',
'ENJ/USDT', 'EOS/USDT', 'ETC/USDT', 'ETH/USDT', 'ETHFI/USDT', 'ETHW/USDT', 'FET/USDT', 'FIDA/USDT', 'FIL/USDT', 'FLOW/USDT', 'FLM/USDT', 'FLUX/USDT', 'FTM/USDT', 'G/USDT', 'GALA/USDT', 'GHST/USDT',
'HMSTR/USDT', 'HOOK/USDT', 'HOT/USDT', 'ICP/USDT', 'ICX/USDT', 'ID/USDT', 'ILV/USDT', 'IMX/USDT', 'IO/USDT', 'IOST/USDT', 'IOTA/USDT', 'IOTX/USDT', 'JASMY/USDT', 'JTO/USDT', 'KAS/USDT',
'LINK/USDT', 'LISTA/USDT', 'LPT/USDT', 'LRC/USDT', 'LSK/USDT', 'LTC/USDT', 'LUNA2/USDT', 'BEL/USDT', 'BICO/USDT', 'BSV/USDT', 'BSW/USDT', 'BTCDOM/USDT', 'BTC/USDT', 'LEVER/USDT', 'LIT/USDT', 'MAGIC/USDT', 'MANA/USDT', 'MASK/USDT', 'MAV/USDT', 'MAVIA/USDT', 'MBOX/USDT', 'MEW/USDT', 'METIS/USDT', 'MKR/USDT', 'MOVR/USDT', 'MYRO/USDT', 'NFP/USDT', 'NEAR/USDT', 'NEIRO/USDT', 
'NEO/USDT', 'NKN/USDT', 'NMR/USDT', 'NTRN/USDT', 'NULS/USDT', 'OGN/USDT', 'OM/USDT', 'OMG/USDT', 'OMNI/USDT', 'ONG/USDT', 'OP/USDT', 'ORBS/USDT', 'PEOPLE/USDT', 'PERP/USDT', 'PHB/USDT', 'PIXEL/USDT',  
'ROSE/USDT', 'RSR/USDT', 'RUNE/USDT', 'SAGA/USDT', 'SAND/USDT', 'SKL/USDT', 'SNX/USDT', 'SOL/USDT', 'SPELL/USDT', 'SFP/USDT', 'KAVA/USDT', 'KDA/USDT', 'KEY/USDT', 'KLAY/USDT', 'KNC/USDT',
'POPCAT/USDT', 'POWR/USDT', 'PORTAL/USDT', 'QTUM/USDT', 'QUICK/USDT', 'QNT/USDT', 'RARE/USDT', 'REEF/USDT', 'REI/USDT', 'REN/USDT', 'RENDER/USDT', 'RLC/USDT', 'RONIN/USDT', 'KSM/USDT', 'LDO/USDT'
]
